const Footer = () => {
  return (
    <>
      <footer className="bg-white border-t mt-12">
        <div className="max-w-6xl mx-auto py-6 px-4 sm:px-6 lg:px-8 text-center text-sm text-gray-500">
          &copy; {new Date().getFullYear()} AutoBlog. All articles generated by
          <span className="text-indigo-700 font-semibold ml-1">LLM scheduler</span>.
        </div>
      </footer>
    </>
  );
};

export default Footer;